name: Check new releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: main
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Check & Commit tailscale/tailscale-android
        uses: ./.github/actions/check-release-action
        with:
          repository: tailscale/tailscale-android

      - name: Git push
        run: |
          git push origin main
          git push origin --tags --force
